### ISSUE TITLE
can't use in Matlab

### ISSUE THREAD

**Issue by ryanorchid** [cstrap/monaco-font#12]
After I executed that command, I can find and choose Monaco in Ubuntu terminal.
But I want to use Monaco in Matlab, I can't find Monaco in Matalab font preferences.
Is anyone knowing how to solve it?
Sincerely, thx~

**Comment by cstrap** [comment]
I think you should ask to matlab group/forum/mailinglist.
Btw, If someone found a solution, feel free to use this issue in order to have docs for users.
Thanks
