### ISSUE TITLE
 I cant find monaco-font in tweaks or terminal settings after I installed it on Ubuntu18.04

### ISSUE THREAD

**Issue by runningyz** [cstrap/monaco-font#18]
cant find monaco-font in tweaks or terminal settings after I installed it on Ubuntu 18.04

**Comment by An-DJ** [comment]
> I've faced the same issue. I've tried with different ways but the steps
> 
> git clone https://github.com/cstrap/monaco-font
> cd monaco-font
> ./install-font-ubuntu.sh http://www.gringod.com/wp-upload/software/Fonts/Monaco_Linux.ttf
> 
> summarized here https://medium.com/@seshumadhav/install-monaco-font-on-ubuntu-670a43814230
> solved the problem

:+1:

**Comment by cstrap** [comment]
I've update the `README.md`.
