### ISSUE TITLE
No anti-aliasing at certain font sizes

### ISSUE THREAD

**Issue by ilyai** [cstrap/monaco-font#2]
When font size is 7 or 9 pt the font rendering is not anti-aliased any more. It looks awful. The same for both normal and bold typefaces. Italic versions are OK though.

![monaco_antialiasing_issue](https://f.cloud.github.com/assets/1911270/1022387/a116657e-0d86-11e3-9ee8-6d2ba802dd4a.png)

**Comment by cstrap** [comment]
Could you try the monaco-font-powerline branch instead of master?
Thanks!

**Comment by cstrap** [comment]
Repo updated. See README, please.
