### ISSUE TITLE
Bad ligatures on Eclipse

### ISSUE THREAD

**Issue by naqern** [cstrap/monaco-font#6]
On some IDEs (I'm using Eclipse but I saw on IntelliJ IDEA too) the last release has bad ligatures (e.g. "f" "i" as in "filter" on 9 and 10 pt). The previous release was fine.

**Comment by cstrap** [comment]
You can try monaco-font-ide branch, there's a different font version

**Comment by cstrap** [comment]
Repo updated. See README.
