### ISSUE TITLE
Can't use it in PhpStorm

### ISSUE THREAD

**Issue by slavafomin** [cstrap/monaco-font#7]
Hello! Thanks for this repository.

I've installed this font on my *Xubuntu* `14.04` machine via provided command line. I can see that font is installed via Font Manager. However, I can't use it in *PhpStorm* (it's just missing from the font list).

Could you elaborate please? Thanks!

PhpStorm trial can be downloaded from here:
https://www.jetbrains.com/phpstorm/download/

**Comment by arresteddeveloper** [comment]
Love this font but also having problems using it in PHPStorm. It's possibly due to missing unicode characters.

I've tried adding the font to my Java's JRE fonts dir as per the link below, but it still doesn't appear as a selectable font.

http://stackoverflow.com/questions/8734216/ttf-fonts-not-available-on-intellij

**Comment by dibalaj** [comment]
Hi! A have this problem too. I see all my fonts, but not Monaco. I tried add it to fonconfig.properties file, but it does not help. How can I enable it for PhpStorm? I really like this font for programming. Thanks for reply.

**Comment by JameChou** [comment]
I have the same problem, I can't use it in Intellij IDEA and WebStorm, but it works well in Ubuntu terminal.

**Comment by duzliang** [comment]
I have the same problem too, I have tried to change the WebStorm setting files, but it doesn't work, I'm really want to know how to fix it

**Comment by cstrap** [comment]
Well, I don't know how WebStorm, PhpStorm or some jetbrains IDEs works.
I've found the same information that @arresteddeveloper has found to solve this issue.

In addition I've found this link https://youtrack.jetbrains.com/issue/IDEA-57233 and it seems an old jetbrains issue not fixed, but I think that some comments could help you.

Dear jetbrains user/devs, this is a call to action :), please help the ubuntu community to find a solution to this issue. Thanks!

**Comment by JameChou** [comment]
Use FontForge can solve this problem.
1. Install FontForge. e.g. Ubuntu sudo apt-get install fontforge
2. Open Monaco_Linux.ttf by FontForge.
3. Ctrl + A choose all font, Hints -> Clear Hints, Hints -> Clear Instructions.
4. Save as <new name>.pdb file.
5. Copy the pdb file to ~/.font.
5. Run sudo fc-cache -f -v to install font.

**Comment by cstrap** [comment]
Great @JameChou ! I didn't know fontforge. 

If it works for all and if the fontforge has a cli I'll try to upgrade the monaco-font script! 
Thanks!

**Comment by duzliang** [comment]
I copy the windows font and install it on ubuntu also solve this problem

**Comment by tomesh** [comment]
Unfortunately, the FontForge did not help (PHPStorm 9, Ubuntu 15,04). I have tried also copying the widnows font to ~/.font but without any success.

From JetBains support I have received a message, that there are some troubles with font format:

http://i.imgur.com/fCEOVmO.png

Can someone see the problem?

**Comment by ahmedash95** [comment]
i think i solve it successfully :D , 

at first download your font ( ex : monaco.ttf ) and then copy it to /user/share/fonts/truetype)

and then open your terminal and type this command $ sudo fc-cache -vf

and then open PHPStorm > File menu > Settings > Editor > Colors & Fonts > Font  

uncheck the show only monospace fonts 

and select your font ( Monaco ) from Primary Font List 

http://i.imgur.com/BFRnmg1.png

enjoy ;)

**Comment by JameChou** [comment]
@tomesh 
Try adding 
```java
-Dawt.useSystemAAFontSettings=on
-Dswing.aatext=true
-Dsun.java2d.xrender=true
```
to the PHPStorm **VM** option file which on `<your_installation_path>/bin/phpwebstorm.vmoptions`.

**Comment by piit79** [comment]
I had the same problem with PhpStorm 9/10, the font just wouldn't show up. I installed the TTF from Windows 7 and it works now. Strange.

**Comment by karborator** [comment]
@ahmedash95 Yep that works for me :)
