### ISSUE TITLE
Font looks ugly on web pages

### ISSUE THREAD

**Issue by sergiolepore** [cstrap/monaco-font#9]
I installed the font today by cloning the repo and running the `install-font-ubuntu.sh` script. It looks great on my editor, but it's really ugly on the web.

![](https://i.imgur.com/tBiWCiD.png)

![](https://i.imgur.com/lAu5M86.png)

**Comment by pacuna** [comment]
+1

**Comment by fonall** [comment]
Re-installing this font by font manager (if you don't have, do an apt-get install command) solves my problem.

**Comment by IonicaBizau** [comment]
Same here! Seems that was introduced after #5. 

Installing [this version](https://github.com/cstrap/monaco-font/raw/141f64f402ac4e804dbf4ffb96667753b1c08ab8/Monaco_Linux.ttf) fixes the pixelized font in pages, but you have to set it using Unity Tweak Tool (e.g. for Gnome Terminal).

![selection_039](https://cloud.githubusercontent.com/assets/2864371/6899883/d0d4cd50-d70b-11e4-9276-3427ba5d00d8.png)

**Comment by sergiolepore** [comment]
@IonicaBizau which Ubuntu release and GTK theme are you using? :)

**Comment by IonicaBizau** [comment]
@sergiolepore I'm using Ubuntu 15.04. See [FAQ, on my website](http://ionicabizau.net/faq). :smile:

**Comment by sergiolepore** [comment]
@IonicaBizau thanks!

**Comment by razouckt** [comment]
This font looks ugly in my editor.

**Comment by cstrap** [comment]
Repo updated: I provide only the script to download/install fonts. 
For the issues on the font please contact the author(s) of the fonts.

**Comment by cstrap** [comment]
Repo updated. See README.
